add failed job for testing

diff --git a/.github/workflows/on-tag-rc.yaml b/.github/workflows/on-tag-rc.yaml
--- a/.github/workflows/on-tag-rc.yaml
+++ b/.github/workflows/on-tag-rc.yaml
@@ -127,4 +127,11 @@ jobs:
           name: main-1234567890-artifact.txt
           path: main-1234567890-artifact.txt
 
+  fail-job:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Fail
+        run: |
+            echo "meant to be failed for testing"
+            exit 1
     
